SELECT DISTINCT B.ID, B.EMAIL, B.FIRST_NAME, B.LAST_NAME
FROM DEVELOPERS B
WHERE EXISTS (
    SELECT 1
    FROM SKILLCODES A
    WHERE A.CATEGORY = 'Front End'
      AND (B.SKILL_CODE & A.CODE) != 0
)
ORDER BY B.ID ASC;
